// export {default as logoSvg} from '@assets/svg/logoSvg';
// export {default as tutorialStep1Svg} from '@assets/svg/tutorialStep1Svg';
// export {default as tutorialStep2Svg} from '@assets/svg/tutorialStep2Svg';
// export {default as tutorialStep3Svg} from '@assets/svg/tutorialStep3Svg';
// export {default as arrowRightSvg} from '@assets/svg/arrowRightSvg';
export {default as iconBackSvg} from '@assets/svg/iconBackSvg';
// export {default as homeSvg} from '@assets/svg/homeSvg';
// export {default as searchSvg} from '@assets/svg/searchSvg';
// export {default as cartSvg} from '@assets/svg/cartSvg';
export {default as iconHomeSvg} from '@assets/svg/BottomBar/iconHomeSvg';
export {default as iconNotifiSvg} from '@assets/svg/BottomBar/iconNotifiSvg';
export {default as iconUtilitiesSvg} from '@assets/svg/BottomBar/iconUtilitiesSvg';
// export {default as logoNHVN} from '@assets/svg/logoNHVN';
// export {default as iconWorkSvg} from '@assets/svg/UtilitiesSvg/iconWorkSvg';
// export {default as iconTransportSvg} from '@assets/svg/UtilitiesSvg/iconTransportSvg';
// export {default as iconXeMaySvg} from '@assets/svg/UtilitiesSvg/iconXeMaySvg';
// export {default as iconFavouriteSvg} from '@assets/svg/UtilitiesSvg/iconFavourite';
// export {default as iconHouseSvg} from '@assets/svg/UtilitiesSvg/iconHouse';
// export {default as iconBuildingsSvg} from '@assets/svg/UtilitiesSvg/iconBuildings';
// export {default as iconPlusSvg} from '@assets/svg/UtilitiesSvg/iconPlus';
// export {default as iconLocationSvg} from '@assets/svg/UtilitiesSvg/iconLocation';
// export {default as iconMonneySvg} from '@assets/svg/UtilitiesSvg/iconMonney';
// export {default as iconAddSvg} from '@assets/svg/IconPSvg/addSvg';
// export {default as iconChatSvg} from '@assets/svg/IconPSvg/chatSvg';
