export namespace PLATFORM {
    let IOS: string;
    let MATERIAL: string;
    let ANDROID: string;
    let DARK: string;
    let LIGHT: string;
    let WEB: string;
}
declare namespace _default {
    export { platformStyle };
    export { platform };
    export { rem };
    export let fontA4SpeedBold: string;
    export let fontDosisLight: string;
    export let fontDosisRegular: string;
    export let barStyleLight: string;
    export let barStyleDark: string;
    export let accordionBorderColor: string;
    export let accordionContentPadding: number;
    export let accordionIconFontSize: number;
    export let contentStyle: string;
    export let expandedIconStyle: string;
    export let headerStyle: string;
    export let iconStyle: string;
    export let disableRow: string;
    export let elevation: number;
    export let containerTouchableBackgroundColor: string;
    export let innerTouchableBackgroundColor: string;
    export let listItemHeight: number;
    export let listItemBorderColor: string;
    export let marginHorizontal: number;
    export let marginLeft: number;
    export let marginTop: number;
    export let minHeight: number;
    export let padding: number;
    export let touchableTextColor: string;
    export let androidRipple: boolean;
    export let androidRippleColor: string;
    export let androidRippleColorDark: string;
    export let buttonUppercaseAndroidText: boolean;
    export let badgeBg: string;
    export let badgeColor: string;
    export let badgePadding: number;
    export let buttonFontFamily: string;
    export let buttonDisabledBg: string;
    export let buttonPadding: number;
    export let buttonDefaultActiveOpacity: number;
    export let buttonDefaultFlex: number;
    export let buttonDefaultBorderRadius: number;
    export let buttonDefaultBorderWidth: number;
    export let buttonFontSize: number;
    export let buttonHeightBase: number;
    export let buttonHeightSmall: number;
    export let buttonHeightLarge: number;
    export let buttonPrimaryBg: string;
    export let buttonPrimaryColor: string;
    export let buttonInfoBg: string;
    export let buttonInfoColor: string;
    export let buttonSuccessBg: string;
    export let buttonSuccessColor: string;
    export let buttonDangerBg: string;
    export let buttonDangerColor: string;
    export let buttonWarningBg: string;
    export let buttonWarningColor: string;
    export let buttonTextSize: number;
    export let buttonTextSizeLarge: number;
    export let buttonTextSizeSmall: number;
    export let borderRadiusLarge: number;
    export let iconSizeLarge: number;
    export let iconSizeSmall: number;
    export let cardDefaultBg: string;
    export let cardBorderColor: string;
    export let cardBorderWidth: number;
    export let cardBorderRadius: number;
    export let cardItemPadding: number;
    export let CheckboxRadius: number;
    export let CheckboxBorderWidth: number;
    export let CheckboxPaddingLeft: number;
    export let CheckboxPaddingBottom: number;
    export let CheckboxIconSize: number;
    export let CheckboxIconMarginTop: number;
    export let CheckboxFontSize: number;
    export let checkboxBgColor: string;
    export let checkboxSize: number;
    export let checkboxTickColor: string;
    export let checkboxDefaultColor: string;
    export let checkboxTextShadowRadius: number;
    export let brandPrimary: string;
    export let brandSecondary: string;
    export let brandSecondary_1: string;
    export let brandSecondary_2: string;
    export let brandSecondary_3: string;
    export let brandSecondary_4: string;
    export let brandFocus: string;
    export let brandInfo: string;
    export let brandSuccess: string;
    export let brandDanger: string;
    export let brandWarning: string;
    export let brandDark: string;
    export let brandGrey: string;
    export let brandLight: string;
    export let tintColorPrimary: string;
    export let opacityTint: number;
    export let brandBgActionSheet: string;
    export let containerBgColor: string;
    export let backgroundMain: string;
    export let backgroundBottomTabs: string;
    export let backgroundBody: string;
    export let backgroundBodyTransparent: string;
    export let backgroundMaskTransparent: string;
    export let backgroundCard: string;
    export let backgroundNavTransparent: string;
    export let skeletonBackground: string;
    export let skeletonHighlight: string;
    export let datePickerFlex: number;
    export let datePickerPadding: number;
    export let datePickerTextColor: string;
    export let datePickerBg: string;
    export let fabBackgroundColor: string;
    export let fabBorderRadius: number;
    export let fabBottom: number;
    export let fabButtonBorderRadius: number;
    export let fabButtonHeight: number;
    export let fabButtonLeft: number;
    export let fabButtonMarginBottom: number;
    export let fabContainerBottom: number;
    export let fabDefaultPosition: number;
    export let fabElevation: number;
    export let fabIconColor: string;
    export let fabIconSize: number;
    export let fabShadowColor: string;
    export let fabShadowOffsetHeight: number;
    export let fabShadowOffsetWidth: number;
    export let fabShadowOpacity: number;
    export let fabShadowRadius: number;
    export let fabWidth: number;
    export let DefaultFontSize: number;
    export let fontFamily: string;
    export let fontSizeBase: number;
    export let fontSizeSmall: number;
    export let fontSizeLarge: number;
    export let fontSizeH1: number;
    export let fontSizeH2: number;
    export let fontSizeH3: number;
    export let fontSizeH4: number;
    export let buttonLineHeight: number;
    export let lineHeightBase: number;
    export let lineHeightH1: number;
    export let lineHeightH2: number;
    export let lineHeightH3: number;
    export let lineHeightH4: number;
    export let lineHeight: number;
    export let listItemSelected: string;
    export let footerHeight: number;
    export let footerDefaultBg: string;
    export let footerPaddingBottom: number;
    export let tabBarTextColor: string;
    export let tabBarTextSize: number;
    export let activeTab: string;
    export let sTabBarActiveTextColor: string;
    export let tabBarActiveTextColor: string;
    export let tabActiveBgColor: string;
    export let tabBar: string;
    export let toolbarBtnColor: string;
    export let toolbarDefaultBg: string;
    export let toolbarSideBarBg: string;
    export let toolbarHeight: number;
    export let toolbarSearchIconSize: number;
    export let toolbarInputColor: string;
    export let searchBarBg: string;
    export let searchBarHeight: number;
    export let searchBarInputHeight: number;
    export let toolbarBtnTextColor: string;
    export let toolbarDefaultBorder: string;
    export let iosStatusbar: string;
    export let statusBarLight: string;
    export let statusBarDark: string;
    export let statusBarColor: any;
    export let statusBarSideBarColor: any;
    export let darkenHeader: any;
    export let iconFamily: string;
    export let iconFontSize: number;
    export let iconHeaderSize: number;
    export let inputFontSize: number;
    export let inputBorderColor: string;
    export let inputSuccessBorderColor: string;
    export let inputErrorBorderColor: string;
    export let inputHeightBase: number;
    export let inputBgBase: string;
    export let inputColor: string;
    export let inputColorPlaceholder: string;
    export let listBg: string;
    export let listBorderColor: string;
    export let listDividerBg: string;
    export let listBtnUnderlayColor: string;
    export let listItemPadding: number;
    export let listNoteColor: string;
    export let listNoteSize: number;
    export let listHeaderColor: string;
    export let listHeaderSize: number;
    export let defaultProgressColor: string;
    export let inverseProgressColor: string;
    export let radioBtnSize: number;
    export let radioSelectedColorAndroid: string;
    export let radioBtnLineHeight: number;
    export let radioColor: string;
    export let segmentBackgroundColor: string;
    export let segmentActiveBackgroundColor: string;
    export let segmentTextColor: string;
    export let segmentActiveTextColor: string;
    export let segmentBorderColor: string;
    export let segmentBorderColorMain: string;
    export let segmentBorderRadius: number;
    export let segmentHeightBase: number;
    export let defaultSpinnerColor: string;
    export let inverseSpinnerColor: string;
    export let tabBarDisabledTextColor: string;
    export let tabDefaultBg: string;
    export let topTabBarTextColor: string;
    export let topTabBarActiveTextColor: string;
    export let topTabBarBorderColor: string;
    export let topTabBarActiveBorderColor: string;
    export let tabBgColor: string;
    export let tabFontSize: number;
    export let textColor: string;
    export let inverseTextColor: string;
    export let noteFontSize: number;
    export let defaultTextColor: string;
    export let titleColor: string;
    export let titleFontfamily: string;
    export let titleFontSize: number;
    export let subTitleFontSize: number;
    export let subtitleColor: string;
    export let titleFontColor: string;
    export let borderRadiusBase: number;
    export let borderWidth: number;
    export let borderColor: string;
    export let contentPadding: number;
    export let dropdownLinkColor: string;
    export let inputLineHeight: number;
    export { deviceWidth };
    export { deviceHeight };
    export { isIphoneX };
    export { isIpad };
    export let inputGroupRoundedBorderRadius: number;
    export namespace Inset {
        namespace portrait {
            let topInset: number;
            let leftInset: number;
            let rightInset: number;
            let bottomInset: number;
        }
        namespace landscape {
            let topInset_1: number;
            export { topInset_1 as topInset };
            let leftInset_1: number;
            export { leftInset_1 as leftInset };
            let rightInset_1: number;
            export { rightInset_1 as rightInset };
            let bottomInset_1: number;
            export { bottomInset_1 as bottomInset };
        }
    }
}
export default _default;
declare const platformStyle: any;
declare const platform: "android" | "ios" | "macos" | "windows" | "web";
declare const rem: number;
declare const deviceWidth: number;
declare const deviceHeight: number;
declare const isIphoneX: boolean;
declare const isIpad: boolean;
